"use client";

import React, { useEffect, useRef } from "react";
import {
  Edit3,
  Globe,
  GitBranch,
  FileText,
  Clock,
  UploadCloud,
} from "lucide-react";
import Card from "./Card";
import { useScroll } from "framer-motion";
import Lenis from "@studio-freight/lenis";

// Features mapped from the Onboard form inputs with colors
const features = [
  {
    name: "1. ONBOARD",
    description: "Set up your pitch workspace",
    details: [
      {
        title: "Startup name",
        text: "Used as the pitch title during the investor simulation.",
      },
      {
        title: "Startup description",
        text: "Explains your problem, solution, users, and vision. This is the primary context Gemini uses to generate investor questions and feedback.",
      },
      {
        title: "Website",
        text: "Helps analyze positioning, messaging, and market clarity. (Optional)",
      },
      {
        title: "Investor pitch deck (PDF / PPTX)",
        text: "Extracts key points like traction, metrics, and ask. Stored securely on Google Cloud Storage and used for RAG-grounded analysis.",
      },
    ],
    icon: Edit3,
    color: "#FF9F7F",
    image: "/setup.webp",
  },
  {
    name: "2. PITCH",
    description: "Simulate a real-world investor conversation",
    details: [
      {
        title: "Live voice pitch simulation",
        text: "Practice your pitch out loud in a realistic investor-style conversation.",
      },
      {
        title: "AI investor questions",
        text: "Get tough, contextual follow-ups generated by Gemini and grounded in YC knowledge.",
      },
      {
        title: "Natural voice interaction",
        text: "Fully voice-driven experience powered by ElevenLabs AI voice agents.",
      },
      {
        title: "Real-time flow control",
        text: "Experience natural interruptions, follow-ups, and pacing—just like a real VC meeting.",
      },
    ],
    icon: Globe,
    color: "#FF794C",
    image: "/banner.webp",
  },
  {
    name: "3. FEEDBACK",
    description: "Understand how your pitch lands with investors",
    details: [
      {
        title: "Structured pitch analysis",
        text: "Receive clear feedback on clarity, structure, delivery, and investor readiness.",
      },
      {
        title: "Investor-grade insights",
        text: "Feedback is grounded using RAG over YC transcripts and your own materials.",
      },
      {
        title: "Spoken feedback",
        text: "Hear your feedback read aloud via ElevenLabs and Anam for a human-like experience.",
      },
      {
        title: "Score-based evaluation",
        text: "Get objective scores across key pitch dimensions to track improvement over time.",
      },
    ],
    icon: GitBranch,
    color: "#FF6632",
    image: "/feedback.webp",
  },
  {
    name: "4. IMPROVE",
    description: "Turn insights into measurable progress",
    details: [
      {
        title: "Actionable improvements",
        text: "Get concrete suggestions on what to fix, clarify, or emphasize.",
      },
      {
        title: "Rewrite recommendations",
        text: "See improved versions of key pitch sections generated by Gemini.",
      },
      {
        title: "Iterate and retry",
        text: "Apply feedback, refine your pitch, and run another simulation instantly.",
      },
      {
        title: "Progress over time",
        text: "Compare past sessions to see how your pitch improves with each iteration.",
      },
    ],
    icon: FileText,
    color: "#FF5319",
    image: "/improve.webp",
  },
];

export default function Features1() {
  const container = useRef(null);

  const { scrollYProgress } = useScroll({
    target: container,
    offset: ["start start", "end end"],
  });

  useEffect(() => {
    const lenis = new Lenis();

    function raf(time: number) {
      lenis.raf(time);
      requestAnimationFrame(raf);
    }

    requestAnimationFrame(raf);

    return () => {
      lenis.destroy();
    };
  }, []);

  return (
    <main ref={container} className="relative">
      {features.map((feature, i) => {
        const targetScale = 1 - (features.length - i) * 0.05;
        return (
          <Card
            key={`feature_${i}`}
            i={i}
            {...feature}
            progress={scrollYProgress}
            range={[i * 0.25, 1]}
            targetScale={targetScale}
          />
        );
      })}
    </main>
  );
}
